baseURL = 'https://kfkhaznernwngts.github.io/kennon/'
languageCode = 'ja'
title = '剣呑'
theme = "simple-style"
enableGitInfo = true
timeZone = "Asia/Tokyo"

[frontmatter]
publishDate = ["publishDate", "date", ":filename", ":default"]
date        = ["date", "publishDate", ":filename", ":default"]
lastmod     = ["lastmod", ":git", "date", ":default"]

[params]
mainSections = ["posts", "post"]
